import '../styles/normalize.css'
import '../styles/style.css'
import '../styles/components-styles/header.css'
import '../styles/components-styles/hero.css'
import '../styles/components-styles/about.css'
import '../animations/scroll-animations.css'
import '../styles/components-styles/contact.css'
import '../styles/components-styles/footer.css'
import '../styles/languages.css'
import '../styles/components-styles/bottom-menu.css'
import '../styles/components-styles/top-menu.css'
import '../styles/utility.css'

